version: "3.8"

services:
  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    container_name: 'user-managment-service-reabbitmq'
    ports:
        - 5672:5672
        - 15672:15672
   
  users-db-debug:
    image: postgres:13
    restart: always
    networks:
      - users-backend
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: Users
    ports:
      - 10001:5432

networks:
  users-backend: {}
